### ISSUE TITLE
Unable to build site on gh-pages

### ISSUE THREAD

**Issue by aditya81070** [munjecrc/munjecrc.github.io#3]
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    github-pages was resolved to 4, which depends on
      jekyll (= 1.1.2)

    jekyll-feed (~> 0.9.3) was resolved to 0.9.3, which depends on
      jekyll (~> 3.3)

**Comment by maddhruv** [comment]
In **Gemfile** remove 'github-pages' Gem at line 18.
The github-pages gem is using a different version of jekyll conflicting with the base jekyll version (3.7.2)

**Comment by maddhruv** [comment]
`# gem "github-pages", group: :jekyll_plugins`

**Comment by aditya81070** [comment]
I comment out  #gem "jekyll", "~> 3.7.2"  this at line 11 to use gh-pages as described in Gemfile comments.

**Comment by maddhruv** [comment]
There's no rule of using 'github-pages' Gem for gh-pages
But you would strictly need the jekyll Gem for jekyll builds
